export const HTTP_STATUS_CODE = {
  SUCCESS_RESPONSE_CODE: 200,
  CREATE_RESPONSE_CODE: 201,
  BAD_REQUEST_RESPONSE_CODE: 400,
  UNAUTHORIZED_RESPONSE_CODE: 401,
  FORBIDDEN_RESPONSE_CODE: 403,
  NOT_FOUND_RESPONSE_CODE: 404,
  CONFLICT_RESPONSE_CODE: 409,
  INTERNAL_SERVER_ERROR_RESPONSE_CODE: 500,
  NOT_IMPLEMENTED_RESPONSE_CODE: 500,
  BAD_GATEWAY_RESPONSE_CODE: 502,
};
